(() => {
'use strict';

const FALLBACK='https://www.dropbox.com/scl/fi/p7jsg38fzmdnqbeayd6b9/Cover.png?rlkey=e8ngjkrda569sy9fwqs0nl4sg&st=43zxzx1l&raw=1';
const MAX_RETRIES=3;
const MIN_CATALOG_SIZE=20;
const CATALOG_CACHE_KEY='eb-catalog-cache-v2';
const safeRead=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(f))}catch{return f}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}};
const state={games:[],q:'',platform:'',setup:'',tags:new Set(),showAll:false,favorites:new Set(safeRead('eb-favorites',[])),recent:safeRead('eb-recent',[]),hidden:new Set(safeRead('eb-hidden',[])),played:new Set(safeRead('eb-played',[])),randomMode:'safe',lastRandom:safeRead('eb-last-random',''),randomPrefs:safeRead('eb-random-prefs',{players:'',platform:'',setup:'',style:'',mode:'safe'}),catalogSource:'none'};
const failedUrls=new Set(safeRead('eb-failed-artwork',[]));
const workingArt=safeRead('eb-working-artwork',{});
const $=s=>document.querySelector(s);
const els={search:$('#search'),platform:$('#platform'),setup:$('#setup'),clear:$('#clearBtn'),more:$('#moreBtn'),shareFilters:$('#shareFilters'),chips:$('#chips'),activeFilters:$('#activeFilters'),grid:$('#gamesGrid'),featured:$('#featuredRail'),quick:$('#quickRail'),friends:$('#friendsRail'),favorites:$('#favoritesRail'),recent:$('#recentRail'),favoritesSection:$('#favoritesSection'),recentSection:$('#recentSection'),count:$('#count'),status:$('#catalogStatus'),modal:$('#modal'),modalImg:$('#modalImg'),modalInner:$('#modalInner'),random:$('#randomBtn'),total:$('#allCount'),brand:$('#brandImg'),brandText:$('#brandText'),toast:$('#toast'),randomizer:$('#randomizer'),randomClose:$('#randomClose'),modeGrid:$('#modeGrid'),randomPlayers:$('#randomPlayers'),randomPlatform:$('#randomPlatform'),randomSetup:$('#randomSetup'),randomStyle:$('#randomStyle'),saveRandomPrefs:$('#saveRandomPrefs'),randomGo:$('#randomGo'),randomReset:$('#randomReset')};
const esc=v=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));
const attr=v=>esc(v).replace(/`/g,'&#96;');
const track=(event,detail={})=>{try{window.EddieTrack?.(event,detail)}catch{}};
function log(type,detail={}){const logs=safeRead('eb-error-log',[]);logs.push({type,detail,at:new Date().toISOString(),ua:navigator.userAgent,path:location.pathname+location.search+location.hash});save('eb-error-log',logs.slice(-120));track(type,detail)}
window.addEventListener('error',e=>log('window_error',{message:e.message,source:e.filename,line:e.lineno,column:e.colno}));
window.addEventListener('unhandledrejection',e=>log('promise_rejection',{message:String(e.reason)}));
function toast(msg){if(!els.toast)return;els.toast.textContent=msg;els.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>els.toast.classList.remove('show'),1900)}

function normalizePlatform(v){const m={playstation:'PlayStation',ps:'PlayStation',ps4:'PlayStation',ps5:'PlayStation',xbox:'Xbox',pc:'PC',windows:'PC',mobile:'Mobile',android:'Mobile',ios:'Mobile',browser:'Browser',web:'Browser',switch:'Switch',nintendo:'Switch',console:'Console',vr:'VR',mac:'Mac',macos:'Mac',linux:'Linux'};return m[String(v||'').toLowerCase()]||String(v||'').trim()}
function normalizeGenre(v){const raw=String(v||'Game').trim();const k=raw.toLowerCase().replace(/[^a-z0-9]+/g,' ' ).trim();const m={'fps':'Shooter','first person shooter':'Shooter','third person shooter':'Shooter','battle royale':'Battle Royale','role playing':'RPG','role playing game':'RPG','massively multiplayer online':'MMO','real time strategy':'Strategy','turn based strategy':'Strategy','sports game':'Sports','party game':'Party','card game':'Cards','social deduction':'Social Deduction','survival game':'Survival','racing game':'Racing','puzzle game':'Puzzle'};return m[k]||raw.replace(/\b\w/g,c=>c.toUpperCase())}
function validPlayers(v){v=String(v||'').trim();if(!v||v.length>24)return'Varies';if(!/(\d|many|massive|varies|players?|solo|team)/i.test(v))return'Varies';return v}
function normalizeSetup(v){const s=String(v||'Check').trim().toLowerCase();if(s.includes('no download')||s==='browser')return'No download';if(s.includes('account'))return'Account';if(s.includes('download'))return'Download';return'Check'}
function normalizeGame(g,id){const title=String(g.title||'').trim();const platforms=[...new Set((Array.isArray(g.platforms)?g.platforms:String(g.platforms||'').split(/\s+/)).filter(Boolean).map(normalizePlatform))];const tags=(Array.isArray(g.tags)?g.tags:String(g.tags||'').split(/\s+/)).map(t=>String(t).toLowerCase()).filter(Boolean);let setup=normalizeSetup(g.setup);if(platforms.includes('Browser')&&setup==='Check')setup='No download';const game={id,title,genre:normalizeGenre(g.genre),platforms,mode:String(g.mode||'Multiplayer').trim(),setup,players:validPlayers(g.players),tags};game.browserVerified=platforms.includes('Browser')&&(setup==='No download'||setup==='Account');game.freeStatus=tags.includes('paid')?'Check price':'Free / free-to-play';return game}
function parseRaw(raw){return String(raw||'').split('|').filter(Boolean).map((row,id)=>{const [title,genre,platforms,mode,setup,players,tags]=row.split('~');return normalizeGame({title,genre,platforms,mode,setup,players,tags},id)})}
function normalizeObjectGames(items){return(items||[]).map((g,id)=>normalizeGame(g,id))}
function dedupe(items){const seen=new Set();const duplicates=[];const clean=items.filter(g=>{const k=g.title.toLowerCase().replace(/[^a-z0-9]/g,'');if(!k)return false;if(seen.has(k)){duplicates.push(g.title);return false}seen.add(k);return true});if(duplicates.length)log('catalog_duplicates_removed',{count:duplicates.length,titles:duplicates.slice(0,20)});return clean}
function validateCatalog(items,source){const clean=dedupe(items).filter(g=>g.title&&g.platforms.length);if(clean.length<MIN_CATALOG_SIZE)throw new Error(`${source} catalog contained only ${clean.length} valid games`);const questionableBrowser=clean.filter(g=>g.platforms.includes('Browser')&&!g.browserVerified).map(g=>g.title);const questionablePlayers=clean.filter(g=>g.players==='Varies').length;if(questionableBrowser.length)log('browser_classification_review',{count:questionableBrowser.length,titles:questionableBrowser.slice(0,30)});if(questionablePlayers)log('player_count_review',{count:questionablePlayers});return clean}
function steamMirrors(url){const m=String(url||'').match(/steam(?:static)?\.com\/steam\/apps\/(\d+)\/header\.jpg|steam\/apps\/(\d+)\/header\.jpg/),id=m&&(m[1]||m[2]);return id?[`https://cdn.cloudflare.steamstatic.com/steam/apps/${id}/header.jpg`,`https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/${id}/header.jpg`,`https://steamcdn-a.akamaihd.net/steam/apps/${id}/header.jpg`]:[]}
const uniqueUrls=v=>[...new Set(v.flat().filter(Boolean).map(String))];
function candidatesFor(g){const previews=window.EDDIE_PREVIEWS||{},art=window.EDDIE_ARTWORK||{},urls=window.EDDIE_URLS||{},primary=previews[g.title],official=urls[g.title],shot=official&&!official.includes('google.com')?`https://image.thum.io/get/width/960/crop/540/noanimate/${official}`:null;const list=uniqueUrls([workingArt[g.title],art[g.title]||[],primary,steamMirrors(primary),shot,FALLBACK]).filter(u=>u===FALLBACK||!failedUrls.has(u));if(!list.includes(FALLBACK))list.push(FALLBACK);return list}
function enrich(items){const urls=window.EDDIE_URLS||{};return items.map((g,id)=>{const artCandidates=candidatesFor(g);return{...g,id,artCandidates,hasArt:artCandidates.some(u=>u!==FALLBACK),url:urls[g.title]||`https://www.google.com/search?q=${encodeURIComponent(g.title+' official game')}`}})}
function retryScript(src,attempt){return new Promise((res,rej)=>{const old=document.querySelector(`script[data-retry-source="${src}"]`);old?.remove();const s=document.createElement('script');s.dataset.retrySource=src;s.src=`${src}?retry=${attempt}&t=${Date.now()}`;s.onload=()=>res();s.onerror=()=>rej(new Error(`Failed to load ${src}`));document.head.appendChild(s)})}
function cacheCatalog(items){save(CATALOG_CACHE_KEY,{savedAt:new Date().toISOString(),items:items.map(({id,artCandidates,hasArt,url,...g})=>g)})}
function cachedCatalog(){const cache=safeRead(CATALOG_CACHE_KEY,null);if(!cache?.items?.length)return null;try{return validateCatalog(normalizeObjectGames(cache.items),'cached')}catch(e){log('cached_catalog_invalid',{message:String(e)});return null}}
async function loadCatalog(){setStatus('loading');for(let attempt=0;attempt<=MAX_RETRIES;attempt++){try{if(window.EDDIE_RAW){const live=validateCatalog(parseRaw(window.EDDIE_RAW),'live');cacheCatalog(live);state.catalogSource='live';track('catalog_loaded',{source:'live',count:live.length,attempt});return enrich(live)}if(attempt<MAX_RETRIES){await retryScript('vault-data.js',attempt+1);await new Promise(r=>setTimeout(r,250*(attempt+1)))}}catch(e){log('catalog_retry_failed',{attempt:attempt+1,message:String(e)})}}
const cached=cachedCatalog();if(cached){state.catalogSource='cache';track('catalog_loaded',{source:'cache',count:cached.length});return enrich(cached)}
if(Array.isArray(window.EDDIE_FALLBACK)&&window.EDDIE_FALLBACK.length){try{const fallback=dedupe(normalizeObjectGames(window.EDDIE_FALLBACK)).filter(g=>g.title&&g.platforms.length);if(fallback.length){state.catalogSource='emergency';log('catalog_emergency_used',{count:fallback.length});return enrich(fallback)}}catch(e){log('catalog_emergency_failed',{message:String(e)})}}
throw new Error('Catalog unavailable')}
function setStatus(type){if(!els.status)return;const m={loading:'<div class="stateCard"><div class="spinner"></div><strong>Getting the games ready…</strong><span>This should only take a moment.</span></div>',unavailable:'<div class="stateCard"><strong>We could not load the game shelf.</strong><span>Check your connection, then try again.</span><button id="retryBtn" type="button">Try Again</button></div>',empty:'<div class="stateCard"><strong>No games match those choices.</strong><span>Try another search or clear your filters.</span></div>'};els.status.innerHTML=m[type]||'';els.status.hidden=!m[type];if(type==='unavailable')$('#retryBtn')?.addEventListener('click',initCatalog)}
const text=g=>[g.title,g.genre,g.platforms.join(' '),g.mode,g.setup,g.players,g.tags.join(' ')].join(' ').toLowerCase();
const usable=g=>g.hasArt&&g.artCandidates.some(u=>u!==FALLBACK&&!failedUrls.has(u));
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
function editDistance(a,b){a=norm(a);b=norm(b);if(!a)return b.length;if(!b)return a.length;const d=Array.from({length:a.length+1},(_,i)=>[i]);for(let j=1;j<=b.length;j++)d[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return d[a.length][b.length]}
function queryMatch(g,q){if(!q)return true;const hay=text(g);if(hay.includes(q))return true;return g.title.split(/\s+/).some(w=>editDistance(w,q)<=1)||editDistance(g.title,q)<=2}
function filtered(){let list=state.games.filter(g=>!state.hidden.has(g.title)&&queryMatch(g,state.q)&&(!state.platform||g.platforms.includes(state.platform))&&(!state.setup||g.setup.toLowerCase()===state.setup.toLowerCase())&&[...state.tags].every(t=>text(g).includes(t)));if(!state.showAll&&!state.q&&!state.platform&&!state.setup&&!state.tags.size)list=list.filter(usable);return list.sort((a,b)=>Number(state.favorites.has(b.title))-Number(state.favorites.has(a.title))||Number(usable(b))-Number(usable(a))||a.title.localeCompare(b.title))}
function persistArtwork(){save('eb-failed-artwork',[...failedUrls].slice(-300));save('eb-working-artwork',workingArt)}
function nextArtwork(img,id,reason='error'){const g=state.games[Number(id)];if(!g)return;const current=img.currentSrc||img.src;if(current&&current!==FALLBACK)failedUrls.add(current);log('image_candidate_failed',{title:g.title,url:current,reason});let i=Number(img.dataset.artIndex||0)+1;while(i<g.artCandidates.length&&failedUrls.has(g.artCandidates[i])&&g.artCandidates[i]!==FALLBACK)i++;if(i>=g.artCandidates.length){img.closest('.art')?.classList.add('imageUnavailable');img.remove();persistArtwork();return}img.dataset.artIndex=String(i);img.src=g.artCandidates[i];persistArtwork()}
function artworkLoaded(img,id){const g=state.games[Number(id)];if(!g)return;const w=img.naturalWidth,h=img.naturalHeight,r=h?w/h:0;if(img.src!==FALLBACK&&(w<300||h<150||r<1.15||r>2.8)){nextArtwork(img,id,'invalid_dimensions');return}img.previousElementSibling?.classList.contains('skeleton')&&img.previousElementSibling.remove();if(img.src===FALLBACK){log('fallback_artwork_shown',{title:g.title});img.closest('.art')?.classList.add('usingFallback')}else{workingArt[g.title]=img.src;persistArtwork()}}
window.ebImgError=(img,id)=>nextArtwork(img,id,'load_error');window.ebImgLoaded=artworkLoaded;
function toggleFavorite(title){state.favorites.has(title)?state.favorites.delete(title):state.favorites.add(title);save('eb-favorites',[...state.favorites]);renderAll();toast(state.favorites.has(title)?'Saved to favorites':'Removed from favorites');track('favorite_changed',{title,saved:state.favorites.has(title)})}
function card(g,eager=false){const first=g.artCandidates.find(u=>!failedUrls.has(u))||FALLBACK,fav=state.favorites.has(g.title);return`<article class="card" tabindex="0" data-id="${g.id}" aria-label="View ${attr(g.title)}"><div class="art"><div class="skeleton"></div><img src="${attr(first)}" data-art-index="${Math.max(0,g.artCandidates.indexOf(first))}" alt="${attr(g.title)} game artwork" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async" onload="ebImgLoaded(this,${g.id})" onerror="ebImgError(this,${g.id})"><button class="favoriteBtn ${fav?'active':''}" type="button" data-favorite="${attr(g.title)}" aria-label="${fav?'Remove from':'Add to'} favorites">${fav?'★':'☆'}</button><div class="badges"><span class="badge ${g.setup.toLowerCase().includes('no')?'easy':''}">${esc(g.setup)}</span><span class="badge">${esc(g.platforms[0]||'Game')}</span></div><div class="posterTitle"><h3>${esc(g.title)}</h3><p>${esc(g.genre)} · ${esc(g.players)}</p></div></div><div class="body"><span>${esc(g.mode)}</span><button class="detailsBtn" type="button">Details</button></div></article>`}
function wire(container){container?.querySelectorAll('[data-favorite]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFavorite(b.dataset.favorite)});container?.querySelectorAll('.card').forEach(c=>{c.onclick=e=>{if(e.target.closest('[data-favorite]'))return;openGame(state.games[Number(c.dataset.id)])};c.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('button')){e.preventDefault();openGame(state.games[Number(c.dataset.id)])}}})}
function fillRail(el,items,eager=false){if(!el)return;el.innerHTML=items.map((g,i)=>card(g,eager&&i<4)).join('');wire(el)}
function renderRails(){const art=state.games.filter(g=>usable(g)&&!state.hidden.has(g.title)),used=new Set();const take=(pred,n=12)=>art.filter(g=>pred(g)&&!used.has(g.title)).slice(0,n).map(g=>(used.add(g.title),g));fillRail(els.featured,take(()=>true,14),true);fillRail(els.quick,take(g=>text(g).includes('browser')||g.setup.toLowerCase().includes('no download'),14));fillRail(els.friends,take(g=>text(g).includes('party')||text(g).includes('co-op')||/4|8|12|16|many|massive/i.test(g.players),14));const favs=state.games.filter(g=>state.favorites.has(g.title)&&!state.hidden.has(g.title));if(els.favoritesSection)els.favoritesSection.hidden=!favs.length;fillRail(els.favorites,favs);const recents=state.recent.map(t=>state.games.find(g=>g.title===t&&!state.hidden.has(g.title))).filter(Boolean).slice(0,12);if(els.recentSection)els.recentSection.hidden=!recents.length;fillRail(els.recent,recents)}
function renderActiveFilters(){if(!els.activeFilters)return;const items=[];if(state.q)items.push(['q',`Search: ${state.q}`]);if(state.platform)items.push(['platform',state.platform]);if(state.setup)items.push(['setup',state.setup]);state.tags.forEach(t=>items.push([`tag:${t}`,t.replace(/\b\w/g,m=>m.toUpperCase())]));els.activeFilters.innerHTML=items.map(([k,l])=>`<button class="activeFilter" data-remove="${attr(k)}" type="button">${esc(l)} ×</button>`).join('');els.activeFilters.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const k=b.dataset.remove;if(k==='q'){state.q='';els.search.value=''}else if(k==='platform'){state.platform='';els.platform.value=''}else if(k==='setup'){state.setup='';els.setup.value=''}else state.tags.delete(k.slice(4));render()})}
function updateUrl(){const p=new URLSearchParams();if(state.q)p.set('q',state.q);if(state.platform)p.set('platform',state.platform);if(state.setup)p.set('setup',state.setup);if(state.tags.size)p.set('tags',[...state.tags].join(','));history.replaceState(null,'',`${location.pathname}${p.toString()?'?'+p:''}${location.hash}`)}
function render(){els.chips?.querySelectorAll('[data-chip]').forEach(b=>b.classList.toggle('active',state.tags.has(b.dataset.chip)));if(els.more){els.more.classList.toggle('active',state.showAll);els.more.textContent=state.showAll?'Top Picks Only':'More Games'}const list=filtered();els.grid.innerHTML=list.map(card).join('');els.count.textContent=`${list.length} game${list.length===1?'':'s'}`;setStatus(list.length?'':'empty');wire(els.grid);renderActiveFilters();updateUrl();track('results_rendered',{count:list.length,hasSearch:Boolean(state.q),filters:state.tags.size+(state.platform?1:0)+(state.setup?1:0)})}
function renderAll(){renderRails();render()}
function setupFilters(){const platforms=[...new Set(state.games.flatMap(g=>g.platforms))].sort();els.platform.innerHTML='<option value="">Any platform</option>'+platforms.map(p=>`<option>${esc(p)}</option>`).join('');els.randomPlatform.innerHTML='<option value="">Any</option>'+platforms.map(p=>`<option>${esc(p)}</option>`).join('');const chips=['browser','no download','party','co-op','shooter','mobile','racing','local','strategy'];els.chips.innerHTML=chips.map(c=>`<button class="chip" type="button" data-chip="${attr(c)}">${esc(c.replace(/\b\w/g,m=>m.toUpperCase()))}</button>`).join('');els.chips.querySelectorAll('[data-chip]').forEach(b=>b.onclick=()=>{const c=b.dataset.chip;state.tags.has(c)?state.tags.delete(c):state.tags.add(c);render()})}
function saveReport(g){const reason=window.prompt('What is wrong? Example: broken link, wrong platform, no longer free, or bad image.');if(reason===null)return;const reports=safeRead('eb-reports',[]);reports.push({title:g.title,reason:String(reason).trim()||'No details provided',url:g.url,at:new Date().toISOString(),page:location.href});save('eb-reports',reports.slice(-150));track('problem_reported',{title:g.title,reason:String(reason).trim().slice(0,120)});toast('Thanks. Your report was saved.')}
async function shareCurrent(){const url=location.href;if(navigator.share)try{await navigator.share({title:"Eddie's Basement",text:'Check out this multiplayer game',url});track('share_completed',{method:'native'});return}catch{}try{await navigator.clipboard.writeText(url);track('share_completed',{method:'clipboard'});toast('Link copied')}catch{toast('Copy the URL to share')}}
function whyThis(g,mode){const bits=[];if(g.setup.toLowerCase().includes('no'))bits.push('it starts fast');if(/4|8|12|16|many|massive/i.test(g.players))bits.push('it works for a group');if(text(g).includes('co-op'))bits.push('you can play together');if(text(g).includes('browser'))bits.push('it runs in a browser');if(mode==='deep')bits.push('it is outside the obvious picks');if(mode==='night')bits.push('it can carry a longer session');return bits.length?`Eddie picked this because ${bits.slice(0,3).join(', ')}.`:'Eddie picked this as a solid fit for the choices you made.'}
function hideGame(g,permanent=false){state.hidden.add(g.title);save('eb-hidden',[...state.hidden]);track('game_hidden',{title:g.title,permanent});toast(permanent?'You will not see this again':'Skipped for tonight');closeModal();renderAll()}
function markPlayed(g){state.played.add(g.title);save('eb-played',[...state.played]);track('game_marked_played',{title:g.title});toast('Marked as played')}
function openGame(g,randomMeta=null){if(!g)return;state.recent=[g.title,...state.recent.filter(t=>t!==g.title)].slice(0,20);save('eb-recent',state.recent);track('game_opened',{title:g.title,random:Boolean(randomMeta)});const first=g.artCandidates.find(u=>!failedUrls.has(u))||FALLBACK;els.modalImg.src=first;els.modalImg.dataset.artIndex=String(Math.max(0,g.artCandidates.indexOf(first)));els.modalImg.alt=`${g.title} artwork`;els.modalImg.onload=()=>artworkLoaded(els.modalImg,g.id);els.modalImg.onerror=()=>nextArtwork(els.modalImg,g.id,'modal_error');const fav=state.favorites.has(g.title),randomBlock=randomMeta?`<span class="randomResultTag">✦ ${esc(randomMeta.label)}</span><div class="whyBox"><b>Why this one?</b><br>${esc(whyThis(g,randomMeta.mode))}</div>`:'';els.modalInner.innerHTML=`${randomBlock}<div class="modalHead"><div><h2>${esc(g.title)}</h2><p>${esc(g.genre)} · ${esc(g.platforms.join(', '))}</p></div><button class="close" id="closeModal" type="button">Close</button></div><div class="facts"><div><b>${esc(g.players)}</b><span>Players</span></div><div><b>${esc(g.setup)}</b><span>Setup</span></div><div><b>${esc(g.mode)}</b><span>Mode</span></div><div><b>${esc(g.platforms.join(', '))}</b><span>Platforms</span></div></div><div class="actions"><a class="action play" href="${attr(g.url)}" target="_blank" rel="noopener noreferrer">Visit Game</a>${randomMeta?'<button class="action pickAgain" id="pickAgain" type="button">Pick Again</button>':''}<button class="action" id="favoriteModal" type="button">${fav?'Remove Favorite':'Save This'}</button><button class="action" id="playedBtn" type="button">Played It</button><button class="action" id="shareGame" type="button">Share</button>${randomMeta?'<button class="action" id="notTonight" type="button">Not Tonight</button><button class="action danger" id="neverShow" type="button">Never Show Again</button>':''}<button class="action" id="reportBtn" type="button">Report a Problem</button></div>`;els.modal.classList.add('open');els.modal.querySelector('.modalCard')?.classList.add('shuffleFlash');setTimeout(()=>els.modal.querySelector('.modalCard')?.classList.remove('shuffleFlash'),450);history.replaceState(null,'',`${location.pathname}${location.search}#game=${encodeURIComponent(g.title)}`);$('#closeModal').onclick=closeModal;$('#favoriteModal').onclick=()=>{toggleFavorite(g.title);openGame(g,randomMeta)};$('#playedBtn').onclick=()=>markPlayed(g);$('#shareGame').onclick=shareCurrent;$('#reportBtn').onclick=()=>saveReport(g);if(randomMeta){$('#pickAgain').onclick=()=>pickRandom(randomMeta.mode,true);$('#notTonight').onclick=()=>hideGame(g,false);$('#neverShow').onclick=()=>hideGame(g,true)}renderRails()}
function closeModal(){els.modal.classList.remove('open');history.replaceState(null,'',location.pathname+location.search)}
function playerMatch(g,value){if(!value)return true;const p=g.players.toLowerCase();if(value==='2')return /2|two/.test(p);if(value==='4')return /4|5|6|7|8|many|massive/.test(p);if(value==='many')return /8|12|16|many|massive|mmo/.test(p);return true}
function randomPool(mode){const pref={players:els.randomPlayers.value,platform:els.randomPlatform.value,setup:els.randomSetup.value,style:els.randomStyle.value};let pool=state.games.filter(g=>usable(g)&&!state.hidden.has(g.title)&&!state.played.has(g.title)&&g.title!==state.lastRandom&&playerMatch(g,pref.players)&&(!pref.platform||g.platforms.includes(pref.platform)));if(pref.setup==='browser')pool=pool.filter(g=>g.browserVerified||g.setup==='No download');if(pref.setup==='download')pool=pool.filter(g=>!g.platforms.includes('Browser'));if(pref.style)pool=pool.filter(g=>text(g).includes(pref.style)||(pref.style==='competitive'&&/shooter|battle|pvp|racing|sports/.test(text(g))));if(mode==='safe')pool=pool.filter(g=>g.setup==='No download'||/party|co-op|casual|browser/.test(text(g)));if(mode==='deep')pool=pool.filter(g=>!state.favorites.has(g.title)&&!state.recent.includes(g.title)).reverse();if(mode==='twenty')pool=pool.filter(g=>g.setup==='No download'||/quick|party|browser|round/.test(text(g)));if(mode==='night')pool=pool.filter(g=>/mmo|rpg|strategy|survival|progression|co-op/.test(text(g)));if(mode==='chaos')pool=state.games.filter(g=>usable(g)&&!state.hidden.has(g.title)&&g.title!==state.lastRandom);return pool}
function pickRandom(mode=state.randomMode,keepOpen=false){const pool=randomPool(mode);const fallback=state.games.filter(g=>usable(g)&&!state.hidden.has(g.title)&&g.title!==state.lastRandom);const source=pool.length?pool:fallback;if(!source.length){toast('No matching games. Try resetting the randomizer.');return}const g=source[Math.floor(Math.random()*source.length)];state.lastRandom=g.title;save('eb-last-random',state.lastRandom);track('random_pick',{title:g.title,mode,poolSize:source.length});if(els.saveRandomPrefs.checked){state.randomPrefs={players:els.randomPlayers.value,platform:els.randomPlatform.value,setup:els.randomSetup.value,style:els.randomStyle.value,mode};save('eb-random-prefs',state.randomPrefs)}if(!keepOpen)closeRandomizer();const labels={safe:'Safe Pick',chaos:'Chaos Mode',deep:'Deep Cut',twenty:'20-Minute Pick',night:'Whole-Night Pick'};openGame(g,{mode,label:labels[mode]||'Eddie Chose'})}
function openRandomizer(){els.randomizer.hidden=false;document.body.style.overflow='hidden';const p=state.randomPrefs||{};state.randomMode=p.mode||'safe';els.randomPlayers.value=p.players||'';els.randomPlatform.value=p.platform||'';els.randomSetup.value=p.setup||'';els.randomStyle.value=p.style||'';els.saveRandomPrefs.checked=Boolean(safeRead('eb-random-prefs',null));els.modeGrid.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.randomMode));els.randomGo.focus();track('randomizer_opened')}
function closeRandomizer(){els.randomizer.hidden=true;document.body.style.overflow=''}
function resetRandomizer(){state.randomMode='safe';els.randomPlayers.value='';els.randomPlatform.value='';els.randomSetup.value='';els.randomStyle.value='';els.saveRandomPrefs.checked=false;localStorage.removeItem('eb-random-prefs');els.modeGrid.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode==='safe'));toast('Randomizer reset')}
function loadUrlState(){const p=new URLSearchParams(location.search);state.q=(p.get('q')||'').toLowerCase();state.platform=p.get('platform')||'';state.setup=p.get('setup')||'';state.tags=new Set((p.get('tags')||'').split(',').filter(Boolean));els.search.value=state.q}
async function initCatalog(){setStatus('loading');els.total.textContent='—';try{state.games=await loadCatalog();els.total.textContent=state.games.length;setupFilters();loadUrlState();els.platform.value=state.platform;els.setup.value=state.setup;renderAll();track('catalog_ready',{count:state.games.length,source:state.catalogSource});const hash=new URLSearchParams(location.hash.replace(/^#/,'')).get('game');if(hash){const g=state.games.find(x=>x.title.toLowerCase()===hash.toLowerCase());if(g)openGame(g)}}catch(e){log('catalog_unavailable',{message:String(e)});els.total.textContent='—';setStatus('unavailable')}}
function initEvents(){els.search.oninput=e=>{state.q=e.target.value.trim().toLowerCase();render()};els.platform.onchange=e=>{state.platform=e.target.value;render()};els.setup.onchange=e=>{state.setup=e.target.value;render()};els.clear.onclick=()=>{state.q='';state.platform='';state.setup='';state.tags.clear();els.search.value='';els.platform.value='';els.setup.value='';render()};els.more.onclick=()=>{state.showAll=!state.showAll;render()};els.shareFilters.onclick=shareCurrent;els.random.onclick=openRandomizer;els.randomClose.onclick=closeRandomizer;els.randomizer.onclick=e=>{if(e.target===els.randomizer)closeRandomizer()};els.modeGrid.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.randomMode=b.dataset.mode;els.modeGrid.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b))});els.randomGo.onclick=()=>pickRandom(state.randomMode);els.randomReset.onclick=resetRandomizer;els.modal.onclick=e=>{if(e.target===els.modal)closeModal()};document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!els.randomizer.hidden)closeRandomizer();else if(els.modal.classList.contains('open'))closeModal()}});els.brand.onerror=()=>{els.brand.style.display='none';els.brandText.style.display='block';log('brand_image_failed')}}
initEvents();initCatalog();
})();