window.EDDIE_PREVIEWS={
'Fortnite':'https://cdn2.unrealengine.com/fortnite-og-social-1920x1080-3c4d9f5f65cb.jpg',
'Roblox':'https://images.rbxcdn.com/076d146437ffc79cebc36bf2ded91196.png',
'Rocket League':'https://cdn.cloudflare.steamstatic.com/steam/apps/252950/header.jpg',
'Valorant':'https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt8e2f8586b27f9f6e/65cfa0e0c6a8495b36f6d3ba/VALORANT_Logo_V.jpg',
'Marvel Rivals':'https://cdn.cloudflare.steamstatic.com/steam/apps/2767030/header.jpg',
'Apex Legends':'https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/header.jpg',
'Overwatch 2':'https://cdn.cloudflare.steamstatic.com/steam/apps/2357570/header.jpg',
'Brawlhalla':'https://cdn.cloudflare.steamstatic.com/steam/apps/291550/header.jpg',
'Fall Guys':'https://cdn.cloudflare.steamstatic.com/steam/apps/1097150/header.jpg',
'Warframe':'https://cdn.cloudflare.steamstatic.com/steam/apps/230410/header.jpg',
'The Finals':'https://cdn.cloudflare.steamstatic.com/steam/apps/2073850/header.jpg',
'Team Fortress 2':'https://cdn.cloudflare.steamstatic.com/steam/apps/440/header.jpg',
'Counter-Strike 2':'https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg',
'Destiny 2':'https://cdn.cloudflare.steamstatic.com/steam/apps/1085660/header.jpg',
'Dauntless':'https://images.ctfassets.net/ww7ek9x6sg2b/6xUL2L8iIGYQ4HZHCLfgSL/7a46a5238cd0f0f591f7e1f51f603354/dauntless-key-art.jpg',
'Path of Exile':'https://cdn.cloudflare.steamstatic.com/steam/apps/238960/header.jpg',
'Guild Wars 2':'https://cdn.cloudflare.steamstatic.com/steam/apps/1284210/header.jpg',
'RuneScape':'https://cdn.cloudflare.steamstatic.com/steam/apps/1343400/header.jpg',
'Old School RuneScape':'https://cdn.cloudflare.steamstatic.com/steam/apps/1343370/header.jpg',
'EVE Online':'https://cdn.cloudflare.steamstatic.com/steam/apps/8500/header.jpg',
'Star Wars: The Old Republic':'https://cdn.cloudflare.steamstatic.com/steam/apps/1286830/header.jpg',
'DC Universe Online':'https://cdn.cloudflare.steamstatic.com/steam/apps/24200/header.jpg',
'Albion Online':'https://cdn.cloudflare.steamstatic.com/steam/apps/761890/header.jpg',
'Lost Ark':'https://cdn.cloudflare.steamstatic.com/steam/apps/1599340/header.jpg',
'World of Tanks Blitz':'https://cdn.cloudflare.steamstatic.com/steam/apps/444200/header.jpg',
'World of Warships':'https://cdn.cloudflare.steamstatic.com/steam/apps/552990/header.jpg',
'War Thunder':'https://cdn.cloudflare.steamstatic.com/steam/apps/236390/header.jpg',
'Enlisted':'https://cdn.cloudflare.steamstatic.com/steam/apps/2051620/header.jpg',
'PUBG: Battlegrounds':'https://cdn.cloudflare.steamstatic.com/steam/apps/578080/header.jpg',
'Call of Duty: Warzone':'https://cdn.cloudflare.steamstatic.com/steam/apps/1938090/header.jpg',
'Halo Infinite Multiplayer':'https://cdn.cloudflare.steamstatic.com/steam/apps/1240440/header.jpg',
'Paladins':'https://cdn.cloudflare.steamstatic.com/steam/apps/444090/header.jpg',
'SMITE 2':'https://cdn.cloudflare.steamstatic.com/steam/apps/2437170/header.jpg',
'Dota 2':'https://cdn.cloudflare.steamstatic.com/steam/apps/570/header.jpg',
'Super Animal Royale':'https://cdn.cloudflare.steamstatic.com/steam/apps/843380/header.jpg',
'Stumble Guys':'https://cdn.cloudflare.steamstatic.com/steam/apps/1677740/header.jpg',
'Farlight 84':'https://cdn.cloudflare.steamstatic.com/steam/apps/1928420/header.jpg',
'Naraka: Bladepoint':'https://cdn.cloudflare.steamstatic.com/steam/apps/1203220/header.jpg',
'Once Human':'https://cdn.cloudflare.steamstatic.com/steam/apps/2139460/header.jpg',
'Palia':'https://cdn.cloudflare.steamstatic.com/steam/apps/2707930/header.jpg',
'Trove':'https://cdn.cloudflare.steamstatic.com/steam/apps/304050/header.jpg',
'Rec Room':'https://cdn.cloudflare.steamstatic.com/steam/apps/471710/header.jpg',
'VRChat':'https://cdn.cloudflare.steamstatic.com/steam/apps/438100/header.jpg',
'Crab Game':'https://cdn.cloudflare.steamstatic.com/steam/apps/1782210/header.jpg',
'Muck':'https://cdn.cloudflare.steamstatic.com/steam/apps/1625450/header.jpg',
'Unturned':'https://cdn.cloudflare.steamstatic.com/steam/apps/304930/header.jpg',
'No More Room in Hell':'https://cdn.cloudflare.steamstatic.com/steam/apps/224260/header.jpg',
'SCP: Secret Laboratory':'https://cdn.cloudflare.steamstatic.com/steam/apps/700330/header.jpg',
'Alien Swarm: Reactive Drop':'https://cdn.cloudflare.steamstatic.com/steam/apps/563560/header.jpg',
'Wolfenstein: Enemy Territory':'https://cdn.cloudflare.steamstatic.com/steam/apps/1873030/header.jpg',
'OpenArena':'https://cdn.cloudflare.steamstatic.com/steam/apps/7650/header.jpg',
'Xonotic':'https://xonotic.org/m/uploads/2018/01/xonotic-banner.jpg',
'Teeworlds':'https://cdn.cloudflare.steamstatic.com/steam/apps/380840/header.jpg',
'Soldat':'https://cdn.cloudflare.steamstatic.com/steam/apps/638490/header.jpg',
'TrackMania Starter Access':'https://cdn.cloudflare.steamstatic.com/steam/apps/2225070/header.jpg',
'Asphalt Legends Unite':'https://cdn.cloudflare.steamstatic.com/steam/apps/1815780/header.jpg',
'Disney Speedstorm':'https://cdn.cloudflare.steamstatic.com/steam/apps/1537830/header.jpg',
'eFootball':'https://cdn.cloudflare.steamstatic.com/steam/apps/1665460/header.jpg',
'Yu-Gi-Oh! Master Duel':'https://cdn.cloudflare.steamstatic.com/steam/apps/1449850/header.jpg',
'Magic: The Gathering Arena':'https://cdn.cloudflare.steamstatic.com/steam/apps/2141910/header.jpg',
'Town of Salem 2':'https://cdn.cloudflare.steamstatic.com/steam/apps/2140510/header.jpg',
'Goose Goose Duck':'https://cdn.cloudflare.steamstatic.com/steam/apps/1568590/header.jpg',
'Mech Arena':'https://cdn.cloudflare.steamstatic.com/steam/apps/2365310/header.jpg',
'Genshin Impact':'https://fastcdn.hoyoverse.com/content-v2/hk4e/124528/b6cd20acc5a85f04650a3085bb28af89_3283168430577658450.jpg',
'Tower of Fantasy':'https://cdn.cloudflare.steamstatic.com/steam/apps/2064650/header.jpg',
'Asphalt 9: Legends':'https://cdn.cloudflare.steamstatic.com/steam/apps/1815780/header.jpg',
'Robocraft':'https://cdn.cloudflare.steamstatic.com/steam/apps/301520/header.jpg',
'Crossout':'https://cdn.cloudflare.steamstatic.com/steam/apps/386180/header.jpg',
'MechWarrior Online':'https://cdn.cloudflare.steamstatic.com/steam/apps/342200/header.jpg',
'Star Conflict':'https://cdn.cloudflare.steamstatic.com/steam/apps/212070/header.jpg',
'OpenTTD':'https://cdn.cloudflare.steamstatic.com/steam/apps/1536610/header.jpg',
'0 A.D.':'https://cdn.cloudflare.steamstatic.com/steam/apps/2190340/header.jpg',
'Beyond All Reason':'https://cdn.cloudflare.steamstatic.com/steam/apps/2980300/header.jpg',
'Mindustry':'https://cdn.cloudflare.steamstatic.com/steam/apps/1127400/header.jpg',
'Wesnoth':'https://cdn.cloudflare.steamstatic.com/steam/apps/599390/header.jpg',
'OpenRA':'https://cdn.cloudflare.steamstatic.com/steam/apps/2229850/header.jpg',
'Board Game Arena':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://boardgamearena.com/',
'Krunker':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://krunker.io/',
'Shell Shockers':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://shellshock.io/',
'1v1.LOL':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://1v1.lol/',
'Smash Karts':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://smashkarts.io/',
'Pokemon Showdown':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://play.pokemonshowdown.com/',
'TETR.IO':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://tetr.io/',
'Skribbl.io':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://skribbl.io/',
'Gartic Phone':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://garticphone.com/',
'Gartic.io':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://gartic.io/',
'Codenames Online':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://codenames.game/',
'Chess.com':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://www.chess.com/',
'Lichess':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://lichess.org/',
'Slither.io':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://slither.io/',
'Agar.io':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://agar.io/',
'Diep.io':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://diep.io/',
'ZombsRoyale.io':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://zombsroyale.io/',
'Bonk.io':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://bonk.io/',
'Starblast.io':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://starblast.io/',
'Territorial.io':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://territorial.io/',
'PlayingCards.io':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://playingcards.io/',
'AirConsole':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://www.airconsole.com/',
'JKLM.fun BombParty':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://jklm.fun/',
'Little Big Snake':'https://image.thum.io/get/width/1200/crop/675/noanimate/https://littlebigsnake.com/'
};
window.EDDIE_URLS={
'Fortnite':'https://www.fortnite.com/','Roblox':'https://www.roblox.com/','Rocket League':'https://www.rocketleague.com/','Valorant':'https://playvalorant.com/','Marvel Rivals':'https://www.marvelrivals.com/','Apex Legends':'https://www.ea.com/games/apex-legends','Overwatch 2':'https://overwatch.blizzard.com/','Brawlhalla':'https://www.brawlhalla.com/','Warframe':'https://www.warframe.com/','Krunker':'https://krunker.io/','Skribbl.io':'https://skribbl.io/','Gartic Phone':'https://garticphone.com/','Codenames Online':'https://codenames.game/','Board Game Arena':'https://boardgamearena.com/','Pokemon Showdown':'https://play.pokemonshowdown.com/','Shell Shockers':'https://shellshock.io/','1v1.LOL':'https://1v1.lol/','Smash Karts':'https://smashkarts.io/','TETR.IO':'https://tetr.io/','Chess.com':'https://www.chess.com/','Lichess':'https://lichess.org/','Slither.io':'https://slither.io/','Agar.io':'https://agar.io/','Diep.io':'https://diep.io/','ZombsRoyale.io':'https://zombsroyale.io/','Bonk.io':'https://bonk.io/','Starblast.io':'https://starblast.io/','Territorial.io':'https://territorial.io/','PlayingCards.io':'https://playingcards.io/','AirConsole':'https://www.airconsole.com/','JKLM.fun BombParty':'https://jklm.fun/'
};