window.EDDIE_PREVIEWS={
  'Brawlhalla':'https://cdn.cloudflare.steamstatic.com/steam/apps/291550/header.jpg',
  'Warframe':'https://cdn.cloudflare.steamstatic.com/steam/apps/230410/header.jpg',
  'Apex Legends':'https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/header.jpg',
  'Team Fortress 2':'https://cdn.cloudflare.steamstatic.com/steam/apps/440/header.jpg',
  'Counter-Strike 2':'https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg',
  'Dota 2':'https://cdn.cloudflare.steamstatic.com/steam/apps/570/header.jpg',
  'Stumble Guys':'https://cdn.cloudflare.steamstatic.com/steam/apps/1677740/header.jpg',
  'Goose Goose Duck':'https://cdn.cloudflare.steamstatic.com/steam/apps/1568590/header.jpg',
  'Unturned':'https://cdn.cloudflare.steamstatic.com/steam/apps/304930/header.jpg',
  'Path of Exile':'https://cdn.cloudflare.steamstatic.com/steam/apps/238960/header.jpg',
  'Albion Online':'https://cdn.cloudflare.steamstatic.com/steam/apps/761890/header.jpg',
  'Guild Wars 2':'https://cdn.cloudflare.steamstatic.com/steam/apps/1284210/header.jpg',
  'Yu-Gi-Oh! Master Duel':'https://cdn.cloudflare.steamstatic.com/steam/apps/1449850/header.jpg',
  'PUBG: Battlegrounds':'https://cdn.cloudflare.steamstatic.com/steam/apps/578080/header.jpg',
  'Old School RuneScape':'https://cdn.cloudflare.steamstatic.com/steam/apps/1343370/header.jpg',
  'RuneScape':'https://cdn.cloudflare.steamstatic.com/steam/apps/1343400/header.jpg',
  'EVE Online':'https://cdn.cloudflare.steamstatic.com/steam/apps/8500/header.jpg',
  'Star Wars: The Old Republic':'https://cdn.cloudflare.steamstatic.com/steam/apps/1286830/header.jpg',
  'DC Universe Online':'https://cdn.cloudflare.steamstatic.com/steam/apps/24200/header.jpg',
  'Lost Ark':'https://cdn.cloudflare.steamstatic.com/steam/apps/1599340/header.jpg',
  'World of Tanks Blitz':'https://cdn.cloudflare.steamstatic.com/steam/apps/444200/header.jpg',
  'World of Warships':'https://cdn.cloudflare.steamstatic.com/steam/apps/552990/header.jpg',
  'War Thunder':'https://cdn.cloudflare.steamstatic.com/steam/apps/236390/header.jpg',
  'Halo Infinite Multiplayer':'https://cdn.cloudflare.steamstatic.com/steam/apps/1240440/header.jpg',
  'Paladins':'https://cdn.cloudflare.steamstatic.com/steam/apps/444090/header.jpg',
  'SMITE 2':'https://cdn.cloudflare.steamstatic.com/steam/apps/2437170/header.jpg',
  'League of Legends':'https://images.contentstack.io/v3/assets/blt731acb42bb3d1659/blt02dd76c15eeda4a9/63ea2b2eb1f08b45b26c1ee5/lol-logo-rendered-hi-res.png',
  'Super Animal Royale':'https://cdn.cloudflare.steamstatic.com/steam/apps/843380/header.jpg',
  'Farlight 84':'https://cdn.cloudflare.steamstatic.com/steam/apps/1928420/header.jpg',
  'Naraka: Bladepoint':'https://cdn.cloudflare.steamstatic.com/steam/apps/1203220/header.jpg',
  'Once Human':'https://cdn.cloudflare.steamstatic.com/steam/apps/2139460/header.jpg',
  'Trove':'https://cdn.cloudflare.steamstatic.com/steam/apps/304050/header.jpg',
  'VRChat':'https://cdn.cloudflare.steamstatic.com/steam/apps/438100/header.jpg',
  'Crab Game':'https://cdn.cloudflare.steamstatic.com/steam/apps/1782210/header.jpg',
  'Muck':'https://cdn.cloudflare.steamstatic.com/steam/apps/1625450/header.jpg',
  'No More Room in Hell':'https://cdn.cloudflare.steamstatic.com/steam/apps/224260/header.jpg',
  'SCP: Secret Laboratory':'https://cdn.cloudflare.steamstatic.com/steam/apps/700330/header.jpg',
  'Alien Swarm: Reactive Drop':'https://cdn.cloudflare.steamstatic.com/steam/apps/563560/header.jpg',
  'TrackMania Starter Access':'https://cdn.cloudflare.steamstatic.com/steam/apps/2225070/header.jpg',
  'Asphalt Legends Unite':'https://cdn.cloudflare.steamstatic.com/steam/apps/1815780/header.jpg',
  'Disney Speedstorm':'https://cdn.cloudflare.steamstatic.com/steam/apps/1537830/header.jpg',
  'eFootball':'https://cdn.cloudflare.steamstatic.com/steam/apps/1665460/header.jpg',
  'Magic: The Gathering Arena':'https://cdn.cloudflare.steamstatic.com/steam/apps/2141910/header.jpg',
  'Hearthstone':'https://d2q63o9r0h0ohi.cloudfront.net/images/cardbacks/cardback_0-2ec208b111e41801206a2a02c7f9f653.png',
  'Board Game Arena':'https://x.boardgamearena.net/data/themereleases/250620-1000/img/layout/logo/logo-bga-horizontal.svg',
  'Krunker':'https://krunker.io/img/logo_1.png',
  'Shell Shockers':'https://shellshock.io/img/shellshockers_logo.png',
  '1v1.LOL':'https://1v1.lol/splash.png',
  'Smash Karts':'https://smashkarts.io/images/logo.png',
  'Pokemon Showdown':'https://play.pokemonshowdown.com/fx/client-logo.png',
  'TETR.IO':'https://tetr.io/res/logo.png',
  'Goose Goose Duck':'https://cdn.cloudflare.steamstatic.com/steam/apps/1568590/header.jpg',
  'Town of Salem 2':'https://cdn.cloudflare.steamstatic.com/steam/apps/2140510/header.jpg',
  'Mech Arena':'https://cdn.cloudflare.steamstatic.com/steam/apps/2365310/header.jpg',
  'Genshin Impact':'https://fastcdn.hoyoverse.com/content-v2/hk4e/124528/b6cd20acc5a85f04650a3085bb28af89_3283168430577658450.jpg',
  'Tower of Fantasy':'https://cdn.cloudflare.steamstatic.com/steam/apps/2064650/header.jpg',
  'Asphalt 9: Legends':'https://cdn.cloudflare.steamstatic.com/steam/apps/1815780/header.jpg',
  'Robocraft':'https://cdn.cloudflare.steamstatic.com/steam/apps/301520/header.jpg',
  'Crossout':'https://cdn.cloudflare.steamstatic.com/steam/apps/386180/header.jpg',
  'MechWarrior Online':'https://cdn.cloudflare.steamstatic.com/steam/apps/342200/header.jpg',
  'Star Conflict':'https://cdn.cloudflare.steamstatic.com/steam/apps/212070/header.jpg',
  'OpenTTD':'https://cdn.cloudflare.steamstatic.com/steam/apps/1536610/header.jpg',
  '0 A.D.':'https://cdn.cloudflare.steamstatic.com/steam/apps/2190340/header.jpg',
  'Mindustry':'https://cdn.cloudflare.steamstatic.com/steam/apps/1127400/header.jpg',
  'Wesnoth':'https://cdn.cloudflare.steamstatic.com/steam/apps/599390/header.jpg',
  'OpenRA':'https://cdn.cloudflare.steamstatic.com/steam/apps/2229850/header.jpg'
};
window.EDDIE_URLS={
  'Fortnite':'https://www.fortnite.com/',
  'Roblox':'https://www.roblox.com/',
  'Rocket League':'https://www.rocketleague.com/',
  'Valorant':'https://playvalorant.com/',
  'Marvel Rivals':'https://www.marvelrivals.com/',
  'Apex Legends':'https://www.ea.com/games/apex-legends',
  'Overwatch 2':'https://overwatch.blizzard.com/',
  'Brawlhalla':'https://www.brawlhalla.com/',
  'Warframe':'https://www.warframe.com/',
  'Krunker':'https://krunker.io/',
  'Skribbl.io':'https://skribbl.io/',
  'Gartic Phone':'https://garticphone.com/',
  'Codenames Online':'https://codenames.game/',
  'Board Game Arena':'https://boardgamearena.com/',
  'Pokemon Showdown':'https://play.pokemonshowdown.com/'
};
